/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import item.conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chotra
 */
public class frmCobros extends javax.swing.JFrame {
    conexion conex;
    Statement ejecutar;
    ResultSet resultado;
    String sentencia;
    char operacion;
    DefaultTableModel tabla = new DefaultTableModel();


    /**
     * Creates new form frmCobros
     */
    public frmCobros() {
        initComponents();
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnro = new javax.swing.JTextField();
        txtclie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCobros = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        txtraz = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnrofact = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtru = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtentrega = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmboxFormadePago = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("REGISTRO DE COBROS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nro Cuotas->");

        txtnro.setEditable(false);
        txtnro.setFocusable(false);

        txtclie.setEditable(false);
        txtclie.setFocusable(false);
        txtclie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtclieActionPerformed(evt);
            }
        });
        txtclie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclieKeyTyped(evt);
            }
        });

        tablaCobros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cobro Nro", "Id Cliente", "Razon Social", "Ruc", "Nro Fact", "Monto Entregado", "Id Cond. Pago", "Descrip Cond Pag"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaCobros.getTableHeader().setReorderingAllowed(false);
        tablaCobros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaCobrosMouseClicked(evt);
            }
        });
        tablaCobros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablaCobrosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaCobros);

        btnAgregar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826392_add_list.png")); // NOI18N
        btnAgregar.setText("Añadir");
        btnAgregar.setToolTipText("click para agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826531_save_as.png")); // NOI18N
        btnGuardar.setText("Aceptar");
        btnGuardar.setToolTipText("click para guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826616_cancel.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("click para cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826672_edit.png")); // NOI18N
        btnModificar.setText("Editar");
        btnModificar.setToolTipText("click para modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826847_gem_cancel_2.png")); // NOI18N
        btnEliminar.setText("Suprimir");
        btnEliminar.setToolTipText("click para eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826965_sign-out.png")); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("click para cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        txtraz.setEditable(false);
        txtraz.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Nro Factura->");

        txtnrofact.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtnrofactCaretUpdate(evt);
            }
        });
        txtnrofact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnrofactActionPerformed(evt);
            }
        });
        txtnrofact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnrofactKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnrofactKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Monto a Pagar->");

        txtMonto.setEditable(false);
        txtMonto.setFocusable(false);
        txtMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoActionPerformed(evt);
            }
        });
        txtMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMontoKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("Condicion de Pago->");

        jLabel14.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\ubicaciones.png")); // NOI18N
        jLabel14.setText("jLabel4");

        txtru.setEditable(false);
        txtru.setFocusable(false);
        txtru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtruActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Cliente->");

        txtentrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentregaActionPerformed(evt);
            }
        });
        txtentrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtentregaKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel10.setText("Monto Entrego->");

        cmboxFormadePago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmboxFormadePagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtnrofact, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmboxFormadePago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtclie, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txtraz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(txtru, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtentrega, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCerrar))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtnrofact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtclie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtraz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtentrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(cmboxFormadePago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabel14)))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtclieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtclieActionPerformed

    private void txtclieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclieKeyTyped

    }//GEN-LAST:event_txtclieKeyTyped

    private void tablaCobrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaCobrosMouseClicked
        cargarCuadros();
    }//GEN-LAST:event_tablaCobrosMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        accionAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        accionGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        accionCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        accionModificar(); // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        accionEliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtnrofactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnrofactKeyTyped
            char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtnrofactKeyTyped

    private void txtMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoActionPerformed

    private void txtMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMontoKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtMontoKeyTyped

    private void txtruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtruActionPerformed

    private void txtentregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentregaActionPerformed

    private void txtentregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtentregaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentregaKeyTyped

    private void txtnrofactCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtnrofactCaretUpdate
      //buscarCliente();        // TODO add your handling code here:
    }//GEN-LAST:event_txtnrofactCaretUpdate

    private void txtnrofactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnrofactKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
            buscarCliente();
           
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_txtnrofactKeyPressed

    private void tablaCobrosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablaCobrosKeyPressed
       if(evt.getKeyCode()==evt.VK_ENTER){
            cargarCuadros();
       }// TODO add your handling code here:
    }//GEN-LAST:event_tablaCobrosKeyPressed

    private void cmboxFormadePagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmboxFormadePagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmboxFormadePagoActionPerformed

    private void txtnrofactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnrofactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnrofactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCobros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCobros().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cmboxFormadePago;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCobros;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtclie;
    private javax.swing.JTextField txtentrega;
    private javax.swing.JTextField txtnro;
    private javax.swing.JTextField txtnrofact;
    private javax.swing.JTextField txtraz;
    private javax.swing.JTextField txtru;
    // End of variables declaration//GEN-END:variables

    private void inicio() {
        try {
            ejecutar = conex.getConexion().createStatement();
            mostrarCobros();
            cargarFormapago();
        } catch (SQLException ex) {
            Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void mostrarCobros() {
        tabla.setRowCount(0);
        tabla = (DefaultTableModel) tablaCobros.getModel();
        sentencia = "SELECT * FROM vistacobro";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            while (resultado.next()){
                Object fila[]= new Object[8];
                fila[0] = resultado.getInt(1);
                fila[1] = resultado.getInt(2);
                fila[2] = resultado.getString(3);
                fila[3] = resultado.getInt(8);
                fila[4] = resultado.getInt(4);
                fila[5] = resultado.getDouble(5);
                  fila[6] = resultado.getString(6);
                   fila[7] = resultado.getString(7);
                
                
                tabla.addRow(fila);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarCuadros() {
        int fsel = tablaCobros.getSelectedRow();
        if(fsel >=0){
            String xnro = tablaCobros.getValueAt(fsel, 0).toString();
            sentencia = "SELECT * FROM vistacobro WHERE idcobro_cuotas = '"+xnro+"'";
            try {
                resultado = ejecutar.executeQuery(sentencia);
                resultado.first();
                txtnro.setText(resultado.getString(1));
                txtnrofact.setText(resultado.getString(4));
                txtclie.setText(resultado.getString(2));
                txtraz.setText(resultado.getString(3));
                txtru.setText(resultado.getString(8));
              
                txtentrega.setText(resultado.getString(5));

            } catch (SQLException ex) {
                //Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void accionAgregar() {
        sentencia = "SELECT MAX(idcobro_cuotas) FROM cobro_cuotas";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            limpiarCuadros();
            txtnro.setText(Integer.toString(resultado.getInt(1) + 1));
            modoEdicion(true);
            operacion = 'A';
            txtnrofact.grabFocus();
        } catch (SQLException ex) {
            Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void modoEdicion(boolean vL) {
        txtMonto.setEnabled(vL);
       txtclie.setEnabled(vL);
        txtentrega.setEnabled(vL);
      txtnro.setEnabled(vL);
      txtnrofact.setEnabled(vL);
       txtraz.setEnabled(vL);
        txtru.setEnabled(vL);
        
        
        btnAgregar.setEnabled(!vL);
        btnGuardar.setEnabled(vL);
        btnCancelar.setEnabled(vL);
        btnModificar.setEnabled(!vL);
        btnEliminar.setEnabled(!vL);
        btnCerrar.setEnabled(!vL);

        tablaCobros.setEnabled(!vL);

    }

    private void limpiarCuadros() {
        txtMonto.setText(null);
        txtclie.setText(null);
        txtentrega.setText(null);
        txtnro.setText(null);
        txtnrofact.setText(null);
        txtraz.setText(null);
        txtru.setText(null);
       
    }

    private void accionModificar() {
        if(tablaCobros.getSelectedRow()>=0){
            operacion = 'M';
            modoEdicion(true);
            txtnrofact.grabFocus();
             } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningun registro", "Seleccione...", JOptionPane.ERROR_MESSAGE);
        }
        }

    private void accionCancelar() {
        modoEdicion(false);
    }

    private void accionGuardar() {
        String v1 = txtnro.getText();
        String v2 = txtclie.getText();
        String v3 = txtnrofact.getText();
        
        String v4 = txtentrega.getText();
        String v5= cmboxFormadePago.getSelectedItem().toString().substring(0, cmboxFormadePago.getSelectedItem().toString().indexOf("-"));
         if (v3.isEmpty()||v5.isEmpty()){
             JOptionPane.showMessageDialog(this, "Debe"+ "ingresar datos"," Revise el casillero vacio",JOptionPane.ERROR_MESSAGE);
            txtnrofact.grabFocus();
         }
         if (operacion == 'A') {
            sentencia = "INSERT INTO cobro_cuotas VALUES('"+v1+"','"+v2+"','"+v3+"','"+v4+"','"+v5+"')";
            
        }
         if (operacion == 'M') {
            sentencia = "UPDATE cobro_cuotas SET idcontactos='"+v2+"',nrofact='"+v3+"',montoEntregado='"+v4+"', idcondiciondepago='"+v5+"' WHERE idcobro_cuotas='"+v1+"'";  
        }
        try {
            ejecutar.executeUpdate(sentencia);
           
        } catch (SQLException ex) {
            //Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
          mostrarCobros();
        modoEdicion(false);
         limpiarCuadros();
    }

    private void accionEliminar() {
       int fsel = tablaCobros.getSelectedRow(); 
       if (fsel>=0){
           String xnro = tablaCobros.getValueAt(fsel, 0).toString();
           String xn = tablaCobros.getValueAt(fsel, 1).toString();
           int resp = JOptionPane.showConfirmDialog(this, "Confirma que desea eliminar la factura nro *"+xn.toUpperCase()+"* del Sistema?","Confirme...",
                    JOptionPane.YES_NO_OPTION);
           if (resp == JOptionPane.YES_OPTION) {
                sentencia = "DELETE FROM cobro_cuotas WHERE idcobro_cuotas= "+xnro+"";
               try {
                   ejecutar.executeUpdate(sentencia);
               } catch (SQLException ex) {
                   Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
               }
               mostrarCobros();
       }
    }
    }

    private void buscarCliente() {
        String xc = txtnrofact.getText();
        sentencia = "select * from facturaventa where nrofact='"+xc+"'AND idformadepago=2";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            txtclie.setText(resultado.getString(20));
            txtraz.setText(resultado.getString(22));
            txtru.setText(resultado.getString(23));
            txtMonto.setText(resultado.getString(16));
            
            
        } catch (SQLException ex) {
            //Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
            txtclie.setText(null);
            txtraz.setText(null);
            txtru.setText(null);
            txtMonto.setText(null);
            txtentrega.setText(null);
        }
    }

    private void cargarFormapago() {
         sentencia = "SELECT * FROM condiciondepago";
        try {
            resultado=ejecutar.executeQuery(sentencia);
             while (resultado.next()) {
                cmboxFormadePago.addItem(resultado.getString(1) + "-> " + resultado.getString(2));
             }
        } catch (SQLException ex) {
            Logger.getLogger(frmCobros.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}