/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import item.conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Chotra
 */
public class frmFactCompras extends javax.swing.JFrame {
    conexion conex;
    Statement ejecutar;
    ResultSet resultado;
    String sentencia, fechaInsert;
    char operacion;
    DefaultTableModel tabla = new DefaultTableModel();
    /**
     * Creates new form frmFactCompras
     */
    public frmFactCompras() {
        initComponents();
        this.setTitle("Modulo de Facturacion - Usuario: "+Inicio.aliasusu);
        try {
            ejecutar = conex.getConexion().createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtclientes = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablafactCompra = new javax.swing.JTable();
        btnItem = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtrazon = new javax.swing.JTextField();
        opCont = new javax.swing.JRadioButton();
        opCredit = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnQuitarItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtruc = new javax.swing.JTextField();
        txtfecha = new javax.swing.JFormattedTextField();
        txtnumero = new javax.swing.JFormattedTextField();
        totExenta = new javax.swing.JFormattedTextField();
        txtTotlIVA5 = new javax.swing.JFormattedTextField();
        txtTotlIVA10 = new javax.swing.JFormattedTextField();
        txtIVA5 = new javax.swing.JFormattedTextField();
        txtIVA10 = new javax.swing.JFormattedTextField();
        txtTotalIVA = new javax.swing.JFormattedTextField();
        txtTotalFactura = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Numero->");

        txtclientes.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtclientesCaretUpdate(evt);
            }
        });
        txtclientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtclientesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtclientesKeyTyped(evt);
            }
        });

        tablafactCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cantidad", "Descripcion", "P.Unitario", "Exenta", "IVA 5%", "IVA 10%"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablafactCompra.getTableHeader().setReorderingAllowed(false);
        tablafactCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablafactCompraMouseClicked(evt);
            }
        });
        tablafactCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tablafactCompraKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablafactCompra);

        btnItem.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826392_add_list.png")); // NOI18N
        btnItem.setText("Añadir Item");
        btnItem.setToolTipText("click para agregar");
        btnItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemActionPerformed(evt);
            }
        });
        btnItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnItemKeyPressed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826531_save_as.png")); // NOI18N
        btnGuardar.setText("Aceptar");
        btnGuardar.setToolTipText("click para guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826616_cancel.png")); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("click para cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCerrar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826965_sign-out.png")); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setToolTipText("click para cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Cliente->");

        txtrazon.setEditable(false);
        txtrazon.setFocusable(false);
        txtrazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtrazonKeyTyped(evt);
            }
        });

        buttonGroup1.add(opCont);
        opCont.setSelected(true);
        opCont.setText("Contado");
        opCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opContActionPerformed(evt);
            }
        });

        buttonGroup1.add(opCredit);
        opCredit.setText("Credito");

        btnAgregar.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826392_add_list.png")); // NOI18N
        btnAgregar.setText("Añadir");
        btnAgregar.setToolTipText("click para agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitarItem.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\1378826847_gem_cancel_2.png")); // NOI18N
        btnQuitarItem.setText("Quitar Item");
        btnQuitarItem.setToolTipText("click para eliminar");
        btnQuitarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarItemActionPerformed(evt);
            }
        });

        jLabel1.setText("Subtotales");

        jLabel3.setText("IVA");

        jLabel4.setText("5%");

        jLabel16.setText("10%");

        jLabel17.setText("Total IVA");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("TOTAL FACTURA");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Fecha->");

        txtruc.setEditable(false);
        txtruc.setFocusable(false);
        txtruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtrucKeyPressed(evt);
            }
        });

        txtfecha.setEditable(false);
        txtfecha.setFocusable(false);

        txtnumero.setEditable(false);
        txtnumero.setFocusable(false);

        totExenta.setEditable(false);
        totExenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        totExenta.setFocusable(false);

        txtTotlIVA5.setEditable(false);
        txtTotlIVA5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtTotlIVA5.setFocusable(false);
        txtTotlIVA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotlIVA5ActionPerformed(evt);
            }
        });

        txtTotlIVA10.setEditable(false);
        txtTotlIVA10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtTotlIVA10.setFocusable(false);

        txtIVA5.setEditable(false);
        txtIVA5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtIVA5.setFocusable(false);

        txtIVA10.setEditable(false);
        txtIVA10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtIVA10.setFocusable(false);

        txtTotalIVA.setEditable(false);
        txtTotalIVA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtTotalIVA.setFocusable(false);

        txtTotalFactura.setEditable(false);
        txtTotalFactura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtTotalFactura.setFocusable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnumero)
                            .addComponent(txtclientes, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfecha)))
                        .addGap(55, 55, 55)
                        .addComponent(opCont)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(opCredit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(totExenta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotlIVA5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTotlIVA10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtIVA5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txtIVA10, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtTotalIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuitarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(158, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(opCont)
                            .addComponent(opCredit)
                            .addComponent(jLabel5)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtclientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrazon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnQuitarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totExenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotlIVA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotlIVA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIVA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIVA10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(txtTotalIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTotalFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtclientesCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtclientesCaretUpdate
        if (txtclientes.getText().length()>0){
            buscarclientes();
        }
    }//GEN-LAST:event_txtclientesCaretUpdate

    private void txtclientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclientesKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){
            insertaCabe();
        }

    }//GEN-LAST:event_txtclientesKeyPressed

    private void txtclientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtclientesKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtclientesKeyTyped

    private void tablafactCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablafactCompraMouseClicked
        cargarCuadros();
    }//GEN-LAST:event_tablafactCompraMouseClicked

    private void tablafactCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tablafactCompraKeyPressed
        if(evt.getKeyCode()==evt.VK_ENTER){
            cargarCuadros();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_tablafactCompraKeyPressed

    private void btnItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemActionPerformed
        nuevoitem();
    }//GEN-LAST:event_btnItemActionPerformed

    private void btnItemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnItemKeyPressed
        if (evt.getKeyCode()==evt.VK_ENTER){

        }

    }//GEN-LAST:event_btnItemKeyPressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        accionGuardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        accionCancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtrazonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrazonKeyTyped
        char car = evt.getKeyChar();
        if((car < '0' || car > '9')){
            evt.consume();
        }
    }//GEN-LAST:event_txtrazonKeyTyped

    private void opContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opContActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        accionAgregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarItemActionPerformed
        quitarItem();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitarItemActionPerformed

    private void txtrucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtrucKeyPressed

    }//GEN-LAST:event_txtrucKeyPressed

    private void txtTotlIVA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotlIVA5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotlIVA5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       mostrarDetalle();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFactCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFactCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFactCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFactCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFactCompras().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnItem;
    private javax.swing.JButton btnQuitarItem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opCont;
    private javax.swing.JRadioButton opCredit;
    private javax.swing.JTable tablafactCompra;
    private javax.swing.JFormattedTextField totExenta;
    private javax.swing.JFormattedTextField txtIVA10;
    private javax.swing.JFormattedTextField txtIVA5;
    private javax.swing.JFormattedTextField txtTotalFactura;
    private javax.swing.JFormattedTextField txtTotalIVA;
    private javax.swing.JFormattedTextField txtTotlIVA10;
    private javax.swing.JFormattedTextField txtTotlIVA5;
    private javax.swing.JTextField txtclientes;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JFormattedTextField txtnumero;
    private javax.swing.JTextField txtrazon;
    private javax.swing.JTextField txtruc;
    // End of variables declaration//GEN-END:variables

    private void cargarCuadros() {
       int fsel = tablafactCompra.getSelectedRow();
        if(fsel>=0){
            String xid = tablafactCompra.getValueAt(fsel, 0).toString();
            sentencia="SELECT * FROM factcompra_encab WHERE nrofact ='"+xid+"'";  
            try {
                resultado = ejecutar.executeQuery(sentencia);
                txtnumero.setText(resultado.getString(1));
                txtfecha.setText(resultado.getString(2));
                txtclientes.setText(resultado.getString(3));
                txtrazon.setText(resultado.getString(4));
                txtruc.setText(resultado.getString(5));
                
                mostrarCompras();
                
            } catch (SQLException ex) {
                Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
}

    private void mostrarCompras() {
        tabla.setRowCount(0);
        tabla=(DefaultTableModel)tablafactCompra.getModel();
        sentencia = "SELECT * FROM factcompra_encab";
        try {
            resultado = ejecutar.executeQuery(sentencia);
             while(resultado.next()){
               Object fila[] = new Object[7];
               fila[0] = resultado.getInt(1);
               fila[1] = resultado.getInt(2);
               fila[2] = resultado.getString(3);
               fila[3] = resultado.getInt(4);
               fila[4] = resultado.getFloat(5);
               fila[5] = resultado.getFloat(6);
               fila[6] = resultado.getFloat(7);
               tabla.addRow(fila);
             }
        } catch (SQLException ex) {
            Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void buscarclientes() {
       String xc = txtclientes.getText();
       sentencia = "select * from contactos where idcontactos='"+xc+"'AND idtipo_cto=1";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            txtrazon.setText(resultado.getString(2));
            txtruc.setText(resultado.getString(3));
        } catch (SQLException ex) {
            //Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
            txtrazon.setText(null);
            txtruc.setText(null);
        }
    }

    private void insertaCabe() {
        String v2 = txtnumero.getText();
        String v1 = fechaInsert;
        String v3 = "";
        if(opCont.isSelected()){
            v3 = "1";
        }else{
            v3 = "2";  
        }
       
        String v4 = txtclientes.getText();
       
       
        sentencia = "INSERT INTO factcompra_encab VALUES('"+v1+"','"+v2+"','"+v3+"','"+v4+"')";
        try {
            ejecutar.executeUpdate(sentencia);
            btnItem.grabFocus();
        } catch (SQLException ex) {
            Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void nuevoitem() {
        String nfact = txtnumero.getText();
        frmBusquedaCompra vb = new frmBusquedaCompra(this, true, "V", nfact);
        vb.setVisible(true);
    }

    private void mostrarDetalle() {
       tabla.setRowCount(0);
       tabla=(DefaultTableModel)tablafactCompra.getModel();
       String nro = txtnumero.getText();
       sentencia = "SELECT *FROM detallecompra WHERE xidcompra = '"+nro+"'";
        try {
            resultado=ejecutar.executeQuery(sentencia);
            while(resultado.next()){
                Object fila[] = new Object[7];
                fila[0]= resultado.getInt(1);
                fila[1]= resultado.getInt(2);
                fila[2]= resultado.getString(3);
                fila[3]= resultado.getDouble(4);
                fila[4]= resultado.getDouble(5);//exenta
                fila[5]= resultado.getDouble(6);//iva5
                fila[6]= resultado.getDouble(7); //iva10
                
                tabla.addRow(fila);
            }
            tablafactCompra.setModel(tabla);
            sentencia = "SELECT * FROM totalcompra WHERE nrofact='"+nro+"'";
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            totExenta.setValue(resultado.getDouble(2));
            txtTotlIVA5.setValue(resultado.getDouble(3));
            txtTotlIVA10.setValue(resultado.getDouble(4));
            txtIVA5.setValue(resultado.getDouble(5));
            txtIVA10.setValue(resultado.getDouble(6));
            txtTotalIVA.setValue(resultado.getDouble(7));
            txtTotalFactura.setValue(resultado.getDouble(8));
            
        } catch (SQLException ex) {
            //Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void accionAgregar() {
        sentencia = "select max(nrofact)from factcompra_encab";
        try {
            resultado = ejecutar.executeQuery(sentencia);
            resultado.first();
            limpiarCuadros();
            txtnumero.setValue(resultado.getInt(1)+1);
            modoEdicion(true);
            operacion='A';
         Date fecha = new Date();
         txtfecha.setValue(fecha);
         SimpleDateFormat formatofecha =  new SimpleDateFormat("yyyy-MM-dd");
        fechaInsert = formatofecha.format(fecha);
        txtclientes.grabFocus();
        } catch (SQLException ex) {
            Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarCuadros() {
        txtIVA10.setText(null);
        txtIVA5.setText(null);
        txtTotalFactura.setText(null);
        txtTotalIVA.setText(null);
        txtTotlIVA10.setText(null);
        txtTotlIVA5.setText(null);
        txtclientes.setText(null);
        txtfecha.setText(null);
        txtnumero.setText(null);
        txtrazon.setText(null);
        txtruc.setText(null);
    }

    private void modoEdicion(boolean vL) {
         txtIVA10.setEnabled(vL);
        txtIVA5.setEnabled(vL);
        txtTotalFactura.setEnabled(vL);
        txtTotalIVA.setEnabled(vL);
        txtTotlIVA10.setEnabled(vL);
        txtTotlIVA5.setEnabled(vL);
        txtclientes.setEnabled(vL);
        txtfecha.setEnabled(vL);
        txtnumero.setEnabled(vL);
        txtrazon.setEnabled(vL);
        txtruc.setEnabled(vL);
        
        btnAgregar.setEnabled(!vL);
        btnCancelar.setEnabled(vL);
        btnCerrar.setEnabled(vL);
        btnQuitarItem.setEnabled(vL);
        btnGuardar.setEnabled(vL);
        btnItem.setEnabled(vL);
        
        
        tablafactCompra.setEnabled(vL);
    }

    private void accionGuardar() {
         int miparametro = Integer.parseInt(txtnumero.getText());
         Map<String, Object> parametro = new HashMap<String, Object>();
         parametro.put("criterio",miparametro);
         
           try {
            JasperReport verreporte = (JasperReport) JRLoader.loadObject(this.getClass().getResource("/reportes/repCompras.jasper"));
            JasperPrint mostrar = JasperFillManager.fillReport(verreporte, parametro, conex.getConexion());
            JasperViewer visor = new JasperViewer(mostrar, false);
            visor.setTitle("Informe del Sistema");
            visor.setVisible(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void accionCancelar() {
         String NroFactura = txtnumero.getText();
         sentencia = "DELETE FROM factcompra_det WHERE nrofact='"+ NroFactura +"'";
        try {
            ejecutar.executeUpdate(sentencia);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Verifique "
                 + "..", "Error al tratar de Cancelar", JOptionPane.ERROR_MESSAGE);
             JOptionPane.showMessageDialog(null, sentencia);
            //Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
        sentencia = "DELETE FROM factcompra_encab WHERE nrofact='"+ NroFactura +"' ";
        try {
            ejecutar.executeUpdate(sentencia);
        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(this, "Verifique "
                 + "..", "Error al tratar de Cancelar", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
           limpiarCuadros();
            mostrarDetalle();
            modoEdicion(false);
    }

    private void accionAnular() {
          String v = JOptionPane.showInputDialog(null, "Ingrese Numero de factura");
          txtnumero.setText(v);
          mostrarDetalle();
          String v1 = txtnumero.getText();
          int a = 1;
          if (v.equals(v1)){
          sentencia = "UPDATE factcompra_encab SET anulado="+a+" where nrofact='"+v1+"'";  
            try {
                ejecutar.executeQuery(sentencia);
                JOptionPane.showMessageDialog(null, "Anulado correctamente");
                limpiarCuadros();
                modoEdicion(
                false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
           "Verifique", "Error al actualizar",JOptionPane.ERROR_MESSAGE);
            }
    }
}

    private void quitarItem() {
        int fsel = tablafactCompra.getSelectedRow();  
          if(fsel>=0){
              String xcod = tablafactCompra.getValueAt(fsel, 0).toString();
              String xn = tablafactCompra.getValueAt(fsel, 1).toString();
              int resp = JOptionPane.showConfirmDialog(this, "Confirma que desea eliminar el item  *"+xn.toUpperCase()+"* del Sistema?","Confirme...",
                    JOptionPane.YES_NO_OPTION);
              if(resp == JOptionPane.YES_OPTION){
                sentencia = "DELETE FROM factcompra_det WHERE idproductos='"+xcod+"'";
                  try {
                      ejecutar.executeUpdate(sentencia);
                  } catch (SQLException ex) {
                      Logger.getLogger(frmFactCompras.class.getName()).log(Level.SEVERE, null, ex);
                  }
                  mostrarDetalle();
          limpiarCuadros();
          }
    }
}
}