/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import item.repFiltrado;
import java.awt.Color;

/**
 *
 * @author Chotra
 */
public class Inicio extends javax.swing.JFrame {
    public static String idusuario="3", aliasusu="Chomi";

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setTitle("Sistema Comercial - Usuario:  "+aliasusu);
        this.getContentPane().setBackground(Color.black);
        this.setExtendedState(6);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        rm = new javax.swing.JMenuItem();
        rs = new javax.swing.JMenuItem();
        rp = new javax.swing.JMenuItem();
        ru = new javax.swing.JMenuItem();
        rc = new javax.swing.JMenuItem();
        rpo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Imarcas = new javax.swing.JMenuItem();
        ISecciones = new javax.swing.JMenuItem();
        Iprocedencia = new javax.swing.JMenuItem();
        Iubicaciones = new javax.swing.JMenuItem();
        rC = new javax.swing.JMenuItem();
        repconComp = new javax.swing.JMenu();
        Rven = new javax.swing.JMenuItem();
        repCobr = new javax.swing.JMenuItem();
        Iproductosor = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        salir = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        facturadeventa = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        facturadeventa1 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema de Productos");

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\NetBeansProjects\\ITEM\\Button Icon\\Fashion_wallpapers_237.jpg")); // NOI18N
        jLabel9.setText("jLabel9");

        jMenu1.setText("Productos");

        rm.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        rm.setText("Marcas");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });
        jMenu1.add(rm);

        rs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        rs.setText("Secciones");
        rs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rsActionPerformed(evt);
            }
        });
        jMenu1.add(rs);

        rp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        rp.setText("Procedencias");
        rp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpActionPerformed(evt);
            }
        });
        jMenu1.add(rp);

        ru.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        ru.setText("Ubicaciones");
        ru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruActionPerformed(evt);
            }
        });
        jMenu1.add(ru);

        rc.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        rc.setText("Categorias");
        rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcActionPerformed(evt);
            }
        });
        jMenu1.add(rc);

        rpo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        rpo.setText("Productos Organizados");
        rpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpoActionPerformed(evt);
            }
        });
        jMenu1.add(rpo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Informes");

        Imarcas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        Imarcas.setText("Marcas");
        Imarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImarcasActionPerformed(evt);
            }
        });
        jMenu2.add(Imarcas);

        ISecciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        ISecciones.setText("Secciones");
        ISecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ISeccionesActionPerformed(evt);
            }
        });
        jMenu2.add(ISecciones);

        Iprocedencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        Iprocedencia.setText("Procedencias");
        Iprocedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IprocedenciaActionPerformed(evt);
            }
        });
        jMenu2.add(Iprocedencia);

        Iubicaciones.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F10, 0));
        Iubicaciones.setText("Ubicaciones");
        Iubicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IubicacionesActionPerformed(evt);
            }
        });
        jMenu2.add(Iubicaciones);

        rC.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, 0));
        rC.setText("Categorias");
        rC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rCActionPerformed(evt);
            }
        });
        jMenu2.add(rC);

        repconComp.setText("Compras");
        repconComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repconCompActionPerformed(evt);
            }
        });
        jMenu2.add(repconComp);

        Rven.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_MINUS, 0));
        Rven.setText("Ventas");
        Rven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RvenActionPerformed(evt);
            }
        });
        jMenu2.add(Rven);

        repCobr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        repCobr.setText("Cobros");
        repCobr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repCobrActionPerformed(evt);
            }
        });
        jMenu2.add(repCobr);

        Iproductosor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        Iproductosor.setText("Productos Organizados");
        Iproductosor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IproductosorActionPerformed(evt);
            }
        });
        jMenu2.add(Iproductosor);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        salir.setText("Salir del Sistema");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu3.add(salir);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Facturacion");

        facturadeventa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, 0));
        facturadeventa.setText("Factura de Venta.");
        facturadeventa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturadeventaActionPerformed(evt);
            }
        });
        jMenu7.add(facturadeventa);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        jMenuItem2.setText("Factura de Compra.");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Cobros");

        facturadeventa1.setText("Cobro de Cuotas");
        facturadeventa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturadeventa1ActionPerformed(evt);
            }
        });
        jMenu8.add(facturadeventa1);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 758, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImarcasActionPerformed
        repFiltrado vrepMarcas = new repFiltrado("repMarcas","Informe Marcas");
        vrepMarcas.setVisible(true);
    }//GEN-LAST:event_ImarcasActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void rpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpoActionPerformed
        frmProductosOrg vprod = new frmProductosOrg(this, true);
        vprod.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_rpoActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed
       frmMarcas vmarcas = new frmMarcas(this, true);
        vmarcas.setVisible(true);
    }//GEN-LAST:event_rmActionPerformed

    private void rpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpActionPerformed
         frmProcedencia vproc = new frmProcedencia(this, true);
        vproc.setVisible(true);
    }//GEN-LAST:event_rpActionPerformed

    private void ruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruActionPerformed
        frmUbicaciones vub = new frmUbicaciones(this, true);
        vub.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ruActionPerformed

    private void rsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rsActionPerformed
        frmSecciones vsecc = new frmSecciones(this, true);
        vsecc.setVisible(true);
    }//GEN-LAST:event_rsActionPerformed

    private void ISeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ISeccionesActionPerformed
        repFiltrado vrepSecciones= new  repFiltrado("repSecciones","Informe Secciones");
        vrepSecciones.setVisible(true);
    }//GEN-LAST:event_ISeccionesActionPerformed

    private void IprocedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IprocedenciaActionPerformed
        repFiltrado vrepProcedencia= new  repFiltrado("repProcedencia","Informe Procedencias");
        vrepProcedencia.setVisible(true);
    }//GEN-LAST:event_IprocedenciaActionPerformed

    private void IubicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IubicacionesActionPerformed
        repFiltrado vrepUbicaciones= new  repFiltrado("repUbicaciones","Informe Ubicaciones");
        vrepUbicaciones.setVisible(true);
    }//GEN-LAST:event_IubicacionesActionPerformed

    private void IproductosorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IproductosorActionPerformed
       repFiltrado vrepProductos= new  repFiltrado("repProductos","Informe Productos");
        vrepProductos.setVisible(true);
    }//GEN-LAST:event_IproductosorActionPerformed

    private void rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcActionPerformed
        frmCategorias vCat = new frmCategorias(this, true);
        vCat.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_rcActionPerformed

    private void rCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rCActionPerformed
        repFiltrado vrepCategorias= new  repFiltrado("repCategorias","InformeCategorias");
        vrepCategorias.setVisible(true);
    }//GEN-LAST:event_rCActionPerformed

    private void facturadeventaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturadeventaActionPerformed
        frmFactVentas vVent = new frmFactVentas();
        vVent.setVisible(true);
    }//GEN-LAST:event_facturadeventaActionPerformed

    private void RvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RvenActionPerformed
        repFiltrado vrepControlVenta= new  repFiltrado("repControlVenta","InformeVentas");
         vrepControlVenta.setVisible(true);
    }//GEN-LAST:event_RvenActionPerformed

    private void facturadeventa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturadeventa1ActionPerformed
          frmCobros vCob = new frmCobros();
        vCob.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_facturadeventa1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       frmFactCompras vcomp = new frmFactCompras();
        vcomp.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void repconCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repconCompActionPerformed
         repFiltrado vrepControlCompras= new  repFiltrado("repControlCompras","InformeVentas");
         vrepControlCompras.setVisible(true); 
    }//GEN-LAST:event_repconCompActionPerformed

    private void repCobrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repCobrActionPerformed
      repFiltrado vrepCobros= new  repFiltrado("repCobros","InformeCobros");
         vrepCobros.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_repCobrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ISecciones;
    private javax.swing.JMenuItem Imarcas;
    private javax.swing.JMenuItem Iprocedencia;
    private javax.swing.JMenuItem Iproductosor;
    private javax.swing.JMenuItem Iubicaciones;
    private javax.swing.JMenuItem Rven;
    private javax.swing.JMenuItem facturadeventa;
    private javax.swing.JMenuItem facturadeventa1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem rC;
    private javax.swing.JMenuItem rc;
    private javax.swing.JMenuItem repCobr;
    private javax.swing.JMenu repconComp;
    private javax.swing.JMenuItem rm;
    private javax.swing.JMenuItem rp;
    private javax.swing.JMenuItem rpo;
    private javax.swing.JMenuItem rs;
    private javax.swing.JMenuItem ru;
    private javax.swing.JMenuItem salir;
    // End of variables declaration//GEN-END:variables
}
